### ISSUE TITLE
mac m1's arm64 cpu seem cann't install this, when I excute "brew install libc-msp430 gdb-msp430"

### ISSUE THREAD

**Issue by enchantessss** [tgtakaoka/homebrew-mspgcc#2]
==> Applying gcc-4.7.0_libiberty-multilib.patch
patching file libiberty/Makefile.in
==> ../configure --target=msp430 --program-prefix=msp430- --prefix=/opt/homebrew/Cellar/gcc-msp430/4.7.0-20120911_2 --enable-languages=c --with-as=/opt/homebrew/bin/msp430-as --with-ld=/opt/homebrew/bin/m
==> make
Last 15 lines from /Users/patrickliu/Library/Logs/Homebrew/gcc-msp430/02.make:
	  cc1-checksum.o main.o  libbackend.a libcommon-target.a libcommon.a ../libcpp/libcpp.a ../libdecnumber/libdecnumber.a libcommon.a ../libcpp/libcpp.a  -liconv ../libiberty/libiberty.a ../libdecnumber/libdecnumber.a    -lmpc -lmpfr -lgmp   -lz
Undefined symbols for architecture arm64:
  "_host_hooks", referenced from:
      _c_common_no_more_pch in c-pch.o
      _toplev_main in libbackend.a(toplev.o)
      _gt_pch_save in libbackend.a(ggc-common.o)
      _gt_pch_restore in libbackend.a(ggc-common.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [cc1] Error 1
make[2]: *** Waiting for unfinished jobs....
mv tmp-specs specs
rm gcc.pod
make[1]: *** [all-gcc] Error 2
make: *** [all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/tgtakaoka/homebrew-mspgcc/issues

**Comment by tgtakaoka** [comment]
Thank you for the report.
However this formula has been deprecated and not maintained.
Please feel free to fork this repository to fix the issue.
